export const customersColumn = [
  {
    field: "user_id",
    headerName: "user_id",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "name",
    headerName: "name",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "tamil_name",
    headerName: "tamil_name",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "alias",
    headerName: "alias",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "email",
    headerName: "email",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "phone",
    headerName: "phone",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "address",
    headerName: "address",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "cibil",
    headerName: "cibil",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
];

// "loan_id": 1,
// "user_id": 1340033214709760,
// "amount": "10000.00",
// "interest_rate": "10.00",
// "loan_type_id": 1,
// "loan_created": "as New",
// "loan_date": "2024-06-05T00:00:00.000Z",
// "start_date": "2024-06-12T00:00:00.000Z",
// "end_date": "2024-08-14T00:00:00.000Z",
// "next_due_date": "2024-06-12T00:00:00.000Z",
// "balance": "10000.00",
// "status": "active",
// "created_at": "2024-06-08T20:37:38.000Z",
// "updated_at": "2024-06-08T20:37:38.000Z",
// "is_deleted": 0,
// "user_name": "Abraham D'Amore Sr.",
// "user_tamil_name": null,
// "user_phone": null,
// "user_address": null,
// "loan_type_name": "THX"

export const loansColumn = [
  {
    field: "loan_id",
    headerName: "loan_id",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "user_id",
    headerName: "user_id",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "user_name",
    headerName: "user_name",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "amount",
    headerName: "amount",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "interest_rate",
    headerName: "interest_rate",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "loan_date",
    headerName: "loan_date",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "next_due_date",
    headerName: "next_due_date",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "balance",
    headerName: "balance",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "status",
    headerName: "status",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
];
