export const customersColumn = [
  {
    field: "user_id",
    headerName: "user_id",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "name",
    headerName: "name",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "tamil_name",
    headerName: "tamil_name",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "alias",
    headerName: "alias",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "email",
    headerName: "email",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "phone",
    headerName: "phone",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "address",
    headerName: "address",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "cibil",
    headerName: "cibil",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
];

export const loansColumn = [
  {
    field: "loan_id",
    headerName: "loan_id",
    minWidth: 100,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "user_id",
    headerName: "user_id",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "user_name",
    headerName: "user_name",
    minWidth: 150,
    flex: 1,
    align: "left",
    pinnable: true,
  },
  {
    field: "amount",
    headerName: "amount",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "interest_rate",
    headerName: "interest_rate",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "loan_date",
    headerName: "loan_date",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "next_due_date",
    headerName: "next_due_date",
    minWidth: 100,
    flex: 1,
    align: "left",
  },
  {
    field: "balance",
    headerName: "balance",
    minWidth: 150,
    flex: 1,
    align: "left",
  },

  {
    field: "due_tenure",
    headerName: "due_tenure",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "due_frequency",
    headerName: "due_frequency",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
  {
    field: "due_time_unit",
    headerName: "due_time_unit",
    minWidth: 150,
    flex: 1,
    align: "left",
  },

  {
    field: "status",
    headerName: "status",
    minWidth: 150,
    flex: 1,
    align: "left",
  },
];
